# Generated by Django 5.2.15 on 2026-07-20 09:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0002_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('sales', 'Sales'), ('expenses', 'Expenses'), ('inventory', 'Inventory'), ('profit-loss', 'Profit & Loss')], max_length=20)),
                ('report_title', models.CharField(max_length=255)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_generations', to='business.business')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_reportgeneration',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'created_at'], name='core_report_busines_c068cb_idx'), models.Index(fields=['business', 'report_type'], name='core_report_busines_7980f8_idx')],
            },
        ),
    ]
