# Generated by Django 5.2.15 on 2026-08-21 10:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_settings'),
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['business', 'expense_date'], name='expenses_ex_busines_42d27c_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['business', 'category'], name='expenses_ex_busines_358a4b_idx'),
        ),
    ]
