# Generated by Django 5.2.15 on 2026-08-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_settings'),
        ('sacco', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['business', 'date'], name='sacco_contr_busines_82e8e0_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['member', 'date'], name='sacco_contr_member__1d2588_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['business', 'status'], name='sacco_loan_busines_c04468_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['business', 'disbursement_date'], name='sacco_loan_busines_ff9c20_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrepayment',
            index=models.Index(fields=['business', 'payment_date'], name='sacco_loanr_busines_53547f_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrepayment',
            index=models.Index(fields=['loan', 'payment_date'], name='sacco_loanr_loan_id_318fb1_idx'),
        ),
        migrations.AddIndex(
            model_name='saccomember',
            index=models.Index(fields=['business', 'status'], name='sacco_membe_busines_2e2f92_idx'),
        ),
    ]
